#!/usr/bin/env bash
# intall nginx web server and configure to port 80
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo sed -i "46i rewrite ^/redirect_me  permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
